<?php

namespace Database\Seeders;

use App\Models\Category;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = [
            // INFANTIL C (6-7 años)
            [
                'name' => 'Infantil C -19 kg',
                'type' => 'Kyorugui',
                'gender' => 'M',
                'min_age' => 6,
                'max_age' => 7,
                'min_weight' => 0,
                'max_weight' => 19,
            ],
            [
                'name' => 'Infantil C -19 kg',
                'type' => 'Kyorugui',
                'gender' => 'F',
                'min_age' => 6,
                'max_age' => 7,
                'min_weight' => 0,
                'max_weight' => 19,
            ],
            [
                'name' => 'Infantil C -23 kg',
                'type' => 'Kyorugui',
                'gender' => 'M',
                'min_age' => 6,
                'max_age' => 7,
                'min_weight' => 19,
                'max_weight' => 23,
            ],
            [
                'name' => 'Infantil C -23 kg',
                'type' => 'Kyorugui',
                'gender' => 'F',
                'min_age' => 6,
                'max_age' => 7,
                'min_weight' => 19,
                'max_weight' => 23,
            ],
            [
                'name' => 'Infantil C -31 kg',
                'type' => 'Kyorugui',
                'gender' => 'M',
                'min_age' => 6,
                'max_age' => 7,
                'min_weight' => 23,
                'max_weight' => 31,
            ],
            [
                'name' => 'Infantil C -31 kg',
                'type' => 'Kyorugui',
                'gender' => 'F',
                'min_age' => 6,
                'max_age' => 7,
                'min_weight' => 23,
                'max_weight' => 31,
            ],
            [
                'name' => 'Infantil C +31 kg',
                'type' => 'Kyorugui',
                'gender' => 'M',
                'min_age' => 6,
                'max_age' => 7,
                'min_weight' => 31,
                'max_weight' => null,
            ],
            [
                'name' => 'Infantil C +31 kg',
                'type' => 'Kyorugui',
                'gender' => 'F',
                'min_age' => 6,
                'max_age' => 7,
                'min_weight' => 31,
                'max_weight' => null,
            ],

            // INFANTIL B (8-9 años)
            [
                'name' => 'Infantil B -21 kg',
                'type' => 'Kyorugui',
                'gender' => 'M',
                'min_age' => 8,
                'max_age' => 9,
                'min_weight' => 0,
                'max_weight' => 21,
            ],
            [
                'name' => 'Infantil B -21 kg',
                'type' => 'Kyorugui',
                'gender' => 'F',
                'min_age' => 8,
                'max_age' => 9,
                'min_weight' => 0,
                'max_weight' => 21,
            ],
            [
                'name' => 'Infantil B -25 kg',
                'type' => 'Kyorugui',
                'gender' => 'M',
                'min_age' => 8,
                'max_age' => 9,
                'min_weight' => 21,
                'max_weight' => 25,
            ],
            [
                'name' => 'Infantil B -25 kg',
                'type' => 'Kyorugui',
                'gender' => 'F',
                'min_age' => 8,
                'max_age' => 9,
                'min_weight' => 21,
                'max_weight' => 25,
            ],
            [
                'name' => 'Infantil B -31 kg',
                'type' => 'Kyorugui',
                'gender' => 'M',
                'min_age' => 8,
                'max_age' => 9,
                'min_weight' => 25,
                'max_weight' => 31,
            ],
            [
                'name' => 'Infantil B -31 kg',
                'type' => 'Kyorugui',
                'gender' => 'F',
                'min_age' => 8,
                'max_age' => 9,
                'min_weight' => 25,
                'max_weight' => 31,
            ],
            [
                'name' => 'Infantil B -36 kg',
                'type' => 'Kyorugui',
                'gender' => 'M',
                'min_age' => 8,
                'max_age' => 9,
                'min_weight' => 31,
                'max_weight' => 36,
            ],
            [
                'name' => 'Infantil B -36 kg',
                'type' => 'Kyorugui',
                'gender' => 'F',
                'min_age' => 8,
                'max_age' => 9,
                'min_weight' => 31,
                'max_weight' => 36,
            ],
            [
                'name' => 'Infantil B +36 kg',
                'type' => 'Kyorugui',
                'gender' => 'M',
                'min_age' => 8,
                'max_age' => 9,
                'min_weight' => 36,
                'max_weight' => null,
            ],
            [
                'name' => 'Infantil B +36 kg',
                'type' => 'Kyorugui',
                'gender' => 'F',
                'min_age' => 8,
                'max_age' => 9,
                'min_weight' => 36,
                'max_weight' => null,
            ],

            // INFANTIL A (10-11 años)
            [
                'name' => 'Infantil A -30 kg',
                'type' => 'Kyorugui',
                'gender' => 'M',
                'min_age' => 10,
                'max_age' => 11,
                'min_weight' => 0,
                'max_weight' => 30,
            ],
            [
                'name' => 'Infantil A -30 kg',
                'type' => 'Kyorugui',
                'gender' => 'F',
                'min_age' => 10,
                'max_age' => 11,
                'min_weight' => 0,
                'max_weight' => 30,
            ],
            [
                'name' => 'Infantil A -35 kg',
                'type' => 'Kyorugui',
                'gender' => 'M',
                'min_age' => 10,
                'max_age' => 11,
                'min_weight' => 30,
                'max_weight' => 35,
            ],
            [
                'name' => 'Infantil A -35 kg',
                'type' => 'Kyorugui',
                'gender' => 'F',
                'min_age' => 10,
                'max_age' => 11,
                'min_weight' => 30,
                'max_weight' => 35,
            ],
            [
                'name' => 'Infantil A -40 kg',
                'type' => 'Kyorugui',
                'gender' => 'M',
                'min_age' => 10,
                'max_age' => 11,
                'min_weight' => 35,
                'max_weight' => 40,
            ],
            [
                'name' => 'Infantil A -40 kg',
                'type' => 'Kyorugui',
                'gender' => 'F',
                'min_age' => 10,
                'max_age' => 11,
                'min_weight' => 35,
                'max_weight' => 40,
            ],
            [
                'name' => 'Infantil A -45 kg',
                'type' => 'Kyorugui',
                'gender' => 'M',
                'min_age' => 10,
                'max_age' => 11,
                'min_weight' => 40,
                'max_weight' => 45,
            ],
            [
                'name' => 'Infantil A -45 kg',
                'type' => 'Kyorugui',
                'gender' => 'F',
                'min_age' => 10,
                'max_age' => 11,
                'min_weight' => 40,
                'max_weight' => 45,
            ],
            [
                'name' => 'Infantil A +45 kg',
                'type' => 'Kyorugui',
                'gender' => 'M',
                'min_age' => 10,
                'max_age' => 11,
                'min_weight' => 45,
                'max_weight' => null,
            ],
            [
                'name' => 'Infantil A +45 kg',
                'type' => 'Kyorugui',
                'gender' => 'F',
                'min_age' => 10,
                'max_age' => 11,
                'min_weight' => 45,
                'max_weight' => null,
            ],
            // CADETE (12-14 años): Peso Mundial
            [
                'name' => 'Cadete -33 kg',
                'type' => 'Kyorugui',
                'gender' => 'M',
                'min_age' => 12,
                'max_age' => 14,
                'min_weight' => 0,
                'max_weight' => 33,
            ],
            [
                'name' => 'Cadete -29 kg',
                'type' => 'Kyorugui',
                'gender' => 'F',
                'min_age' => 12,
                'max_age' => 14,
                'min_weight' => 0,
                'max_weight' => 29,
            ],
            [
                'name' => 'Cadete -37 kg',
                'type' => 'Kyorugui',
                'gender' => 'M',
                'min_age' => 12,
                'max_age' => 14,
                'min_weight' => 33,
                'max_weight' => 37,
            ],
            [
                'name' => 'Cadete -33 kg',
                'type' => 'Kyorugui',
                'gender' => 'F',
                'min_age' => 12,
                'max_age' => 14,
                'min_weight' => 29,
                'max_weight' => 33,
            ],
            [
                'name' => 'Cadete -41 kg',
                'type' => 'Kyorugui',
                'gender' => 'M',
                'min_age' => 12,
                'max_age' => 14,
                'min_weight' => 37,
                'max_weight' => 41,
            ],
            [
                'name' => 'Cadete -37 kg',
                'type' => 'Kyorugui',
                'gender' => 'F',
                'min_age' => 12,
                'max_age' => 14,
                'min_weight' => 33,
                'max_weight' => 37,
            ],
            [
                'name' => 'Cadete -45 kg',
                'type' => 'Kyorugui',
                'gender' => 'M',
                'min_age' => 12,
                'max_age' => 14,
                'min_weight' => 41,
                'max_weight' => 45,
            ],
            [
                'name' => 'Cadete -41 kg',
                'type' => 'Kyorugui',
                'gender' => 'F',
                'min_age' => 12,
                'max_age' => 14,
                'min_weight' => 37,
                'max_weight' => 41,
            ],
            [
                'name' => 'Cadete -49 kg',
                'type' => 'Kyorugui',
                'gender' => 'M',
                'min_age' => 12,
                'max_age' => 14,
                'min_weight' => 45,
                'max_weight' => 49,
            ],
            [
                'name' => 'Cadete -44 kg',
                'type' => 'Kyorugui',
                'gender' => 'F',
                'min_age' => 12,
                'max_age' => 14,
                'min_weight' => 41,
                'max_weight' => 44,
            ],
            [
                'name' => 'Cadete -53 kg',
                'type' => 'Kyorugui',
                'gender' => 'M',
                'min_age' => 12,
                'max_age' => 14,
                'min_weight' => 49,
                'max_weight' => 53,
            ],
            [
                'name' => 'Cadete -47 kg',
                'type' => 'Kyorugui',
                'gender' => 'F',
                'min_age' => 12,
                'max_age' => 14,
                'min_weight' => 44,
                'max_weight' => 47,
            ],
            [
                'name' => 'Cadete -57 kg',
                'type' => 'Kyorugui',
                'gender' => 'M',
                'min_age' => 12,
                'max_age' => 14,
                'min_weight' => 53,
                'max_weight' => 57,
            ],
            [
                'name' => 'Cadete -51 kg',
                'type' => 'Kyorugui',
                'gender' => 'F',
                'min_age' => 12,
                'max_age' => 14,
                'min_weight' => 47,
                'max_weight' => 51,
            ],
            [
                'name' => 'Cadete -61 kg',
                'type' => 'Kyorugui',
                'gender' => 'M',
                'min_age' => 12,
                'max_age' => 14,
                'min_weight' => 57,
                'max_weight' => 61,
            ],
            [
                'name' => 'Cadete -55 kg',
                'type' => 'Kyorugui',
                'gender' => 'F',
                'min_age' => 12,
                'max_age' => 14,
                'min_weight' => 51,
                'max_weight' => 55,
            ],
            [
                'name' => 'Cadete -65 kg',
                'type' => 'Kyorugui',
                'gender' => 'M',
                'min_age' => 12,
                'max_age' => 14,
                'min_weight' => 61,
                'max_weight' => 65,
            ],
            [
                'name' => 'Cadete -59 kg',
                'type' => 'Kyorugui',
                'gender' => 'F',
                'min_age' => 12,
                'max_age' => 14,
                'min_weight' => 55,
                'max_weight' => 59,
            ],
            [
                'name' => 'Cadete +65 kg',
                'type' => 'Kyorugui',
                'gender' => 'M',
                'min_age' => 12,
                'max_age' => 14,
                'min_weight' => 65,
                'max_weight' => null,
            ],
            [
                'name' => 'Cadete +59 kg',
                'type' => 'Kyorugui',
                'gender' => 'F',
                'min_age' => 12,
                'max_age' => 14,
                'min_weight' => 59,
                'max_weight' => null,
            ],
             // JUVENIL (15-17 años): Peso Mundial
             [
                'name' => 'Juvenil -45 kg',
                'type' => 'Kyorugui',
                'gender' => 'M',
                'min_age' => 15,
                'max_age' => 17,
                'min_weight' => 0,
                'max_weight' => 45,
            ],
            [
                'name' => 'Juvenil -42 kg',
                'type' => 'Kyorugui',
                'gender' => 'F',
                'min_age' => 15,
                'max_age' => 17,
                'min_weight' => 0,
                'max_weight' => 42,
            ],
            [
                'name' => 'Juvenil -48 kg',
                'type' => 'Kyorugui',
                'gender' => 'M',
                'min_age' => 15,
                'max_age' => 17,
                'min_weight' => 45,
                'max_weight' => 48,
            ],
            [
                'name' => 'Juvenil -44 kg',
                'type' => 'Kyorugui',
                'gender' => 'F',
                'min_age' => 15,
                'max_age' => 17,
                'min_weight' => 42,
                'max_weight' => 44,
            ],
            [
                'name' => 'Juvenil -51 kg',
                'type' => 'Kyorugui',
                'gender' => 'M',
                'min_age' => 15,
                'max_age' => 17,
                'min_weight' => 48,
                'max_weight' => 51,
            ],
            [
                'name' => 'Juvenil -46 kg',
                'type' => 'Kyorugui',
                'gender' => 'F',
                'min_age' => 15,
                'max_age' => 17,
                'min_weight' => 44,
                'max_weight' => 46,
            ],
            [
                'name' => 'Juvenil -55 kg',
                'type' => 'Kyorugui',
                'gender' => 'M',
                'min_age' => 15,
                'max_age' => 17,
                'min_weight' => 51,
                'max_weight' => 55,
            ],
            [
                'name' => 'Juvenil -49 kg',
                'type' => 'Kyorugui',
                'gender' => 'F',
                'min_age' => 15,
                'max_age' => 17,
                'min_weight' => 46,
                'max_weight' => 49,
            ],
            [
                'name' => 'Juvenil -59 kg',
                'type' => 'Kyorugui',
                'gender' => 'M',
                'min_age' => 15,
                'max_age' => 17,
                'min_weight' => 55,
                'max_weight' => 59,
            ],
            [
                'name' => 'Juvenil -52 kg',
                'type' => 'Kyorugui',
                'gender' => 'F',
                'min_age' => 15,
                'max_age' => 17,
                'min_weight' => 49,
                'max_weight' => 52,
            ],
            [
                'name' => 'Juvenil -63 kg',
                'type' => 'Kyorugui',
                'gender' => 'M',
                'min_age' => 15,
                'max_age' => 17,
                'min_weight' => 59,
                'max_weight' => 63,
            ],
            [
                'name' => 'Juvenil -55 kg',
                'type' => 'Kyorugui',
                'gender' => 'F',
                'min_age' => 15,
                'max_age' => 17,
                'min_weight' => 52,
                'max_weight' => 55,
            ],
            [
                'name' => 'Juvenil -68 kg',
                'type' => 'Kyorugui',
                'gender' => 'M',
                'min_age' => 15,
                'max_age' => 17,
                'min_weight' => 63,
                'max_weight' => 68,
            ],
            [
                'name' => 'Juvenil -59 kg',
                'type' => 'Kyorugui',
                'gender' => 'F',
                'min_age' => 15,
                'max_age' => 17,
                'min_weight' => 55,
                'max_weight' => 59,
            ],
            [
                'name' => 'Juvenil -73 kg',
                'type' => 'Kyorugui',
                'gender' => 'M',
                'min_age' => 15,
                'max_age' => 17,
                'min_weight' => 68,
                'max_weight' => 73,
            ],
            [
                'name' => 'Juvenil -63 kg',
                'type' => 'Kyorugui',
                'gender' => 'F',
                'min_age' => 15,
                'max_age' => 17,
                'min_weight' => 59,
                'max_weight' => 63,
            ],
            [
                'name' => 'Juvenil -78 kg',
                'type' => 'Kyorugui',
                'gender' => 'M',
                'min_age' => 15,
                'max_age' => 17,
                'min_weight' => 73,
                'max_weight' => 78,
            ],
            [
                'name' => 'Juvenil -68 kg',
                'type' => 'Kyorugui',
                'gender' => 'F',
                'min_age' => 15,
                'max_age' => 17,
                'min_weight' => 63,
                'max_weight' => 68,
            ],
            [
                'name' => 'Juvenil +78 kg',
                'type' => 'Kyorugui',
                'gender' => 'M',
                'min_age' => 15,
                'max_age' => 17,
                'min_weight' => 78,
                'max_weight' => null,
            ],
            [
                'name' => 'Juvenil +68 kg',
                'type' => 'Kyorugui',
                'gender' => 'F',
                'min_age' => 15,
                'max_age' => 17,
                'min_weight' => 68,
                'max_weight' => null,
            ],
            // ADULTO (+18 años): Peso Mundial
            [
                'name' => 'Adulto -54 kg',
                'type' => 'Kyorugui',
                'gender' => 'M',
                'min_age' => 18,
                'max_age' => null,
                'min_weight' => 0,
                'max_weight' => 54,
            ],
            [
                'name' => 'Adulto -46 kg',
                'type' => 'Kyorugui',
                'gender' => 'F',
                'min_age' => 18,
                'max_age' => null,
                'min_weight' => 0,
                'max_weight' => 46,
            ],
            [
                'name' => 'Adulto -58 kg',
                'type' => 'Kyorugui',
                'gender' => 'M',
                'min_age' => 18,
                'max_age' => null,
                'min_weight' => 54,
                'max_weight' => 58,
            ],
            [
                'name' => 'Adulto -49 kg',
                'type' => 'Kyorugui',
                'gender' => 'F',
                'min_age' => 18,
                'max_age' => null,
                'min_weight' => 46,
                'max_weight' => 49,
            ],
            [
                'name' => 'Adulto -63 kg',
                'type' => 'Kyorugui',
                'gender' => 'M',
                'min_age' => 18,
                'max_age' => null,
                'min_weight' => 58,
                'max_weight' => 63,
            ],
            [
                'name' => 'Adulto -53 kg',
                'type' => 'Kyorugui',
                'gender' => 'F',
                'min_age' => 18,
                'max_age' => null,
                'min_weight' => 49,
                'max_weight' => 53,
            ],
            [
                'name' => 'Adulto -68 kg',
                'type' => 'Kyorugui',
                'gender' => 'M',
                'min_age' => 18,
                'max_age' => null,
                'min_weight' => 63,
                'max_weight' => 68,
            ],
            [
                'name' => 'Adulto -57 kg',
                'type' => 'Kyorugui',
                'gender' => 'F',
                'min_age' => 18,
                'max_age' => null,
                'min_weight' => 53,
                'max_weight' => 57,
            ],
            [
                'name' => 'Adulto -74 kg',
                'type' => 'Kyorugui',
                'gender' => 'M',
                'min_age' => 18,
                'max_age' => null,
                'min_weight' => 68,
                'max_weight' => 74,
            ],
            [
                'name' => 'Adulto -62 kg',
                'type' => 'Kyorugui',
                'gender' => 'F',
                'min_age' => 18,
                'max_age' => null,
                'min_weight' => 57,
                'max_weight' => 62,
            ],
            [
                'name' => 'Adulto -80 kg',
                'type' => 'Kyorugui',
                'gender' => 'M',
                'min_age' => 18,
                'max_age' => null,
                'min_weight' => 74,
                'max_weight' => 80,
            ],
            [
                'name' => 'Adulto -67 kg',
                'type' => 'Kyorugui',
                'gender' => 'F',
                'min_age' => 18,
                'max_age' => null,
                'min_weight' => 62,
                'max_weight' => 67,
            ],
            [
                'name' => 'Adulto -87 kg',
                'type' => 'Kyorugui',
                'gender' => 'M',
                'min_age' => 18,
                'max_age' => null,
                'min_weight' => 80,
                'max_weight' => 87,
            ],
            [
                'name' => 'Adulto -73 kg',
                'type' => 'Kyorugui',
                'gender' => 'F',
                'min_age' => 18,
                'max_age' => null,
                'min_weight' => 67,
                'max_weight' => 73,
            ],
            [
                'name' => 'Adulto +87 kg',
                'type' => 'Kyorugui',
                'gender' => 'M',
                'min_age' => 18,
                'max_age' => null,
                'min_weight' => 87,
                'max_weight' => null,
            ],
            [
                'name' => 'Adulto +73 kg',
                'type' => 'Kyorugui',
                'gender' => 'F',
                'min_age' => 18,
                'max_age' => null,
                'min_weight' => 73,
                'max_weight' => null,
            ],
           
          
            // PARA-KYORUGUI
            // ADULTO (+18 años): Peso Olímpico
            [
                'name' => 'Adulto -58 kg',
                'type' => 'Para-Kyorugui',
                'gender' => 'M',
                'min_age' => 18,
                'max_age' => null,
                'min_weight' => 0,
                'max_weight' => 58,
            ],
            [
                'name' => 'Adulto -49 kg',
                'type' => 'Para-Kyorugui',
                'gender' => 'F',
                'min_age' => 18,
                'max_age' => null,
                'min_weight' => 0,
                'max_weight' => 49,
            ],
            [
                'name' => 'Adulto -68 kg',
                'type' => 'Para-Kyorugui',
                'gender' => 'M',
                'min_age' => 18,
                'max_age' => null,
                'min_weight' => 58,
                'max_weight' => 68,
            ],
            [
                'name' => 'Adulto -57 kg',
                'type' => 'Para-Kyorugui',
                'gender' => 'F',
                'min_age' => 18,
                'max_age' => null,
                'min_weight' => 49,
                'max_weight' => 57,
            ],
            [
                'name' => 'Adulto -80 kg',
                'type' => 'Para-Kyorugui',
                'gender' => 'M',
                'min_age' => 18,
                'max_age' => null,
                'min_weight' => 68,
                'max_weight' => 80,
            ],
            [
                'name' => 'Adulto -67 kg',
                'type' => 'Para-Kyorugui',
                'gender' => 'F',
                'min_age' => 18,
                'max_age' => null,
                'min_weight' => 57,
                'max_weight' => 67,
            ],
            [
                'name' => 'Adulto +80 kg',
                'type' => 'Para-Kyorugui',
                'gender' => 'M',
                'min_age' => 18,
                'max_age' => null,
                'min_weight' => 80,
                'max_weight' => null,
            ],
            [
                'name' => 'Adulto +67 kg',
                'type' => 'Para-Kyorugui',
                'gender' => 'F',
                'min_age' => 18,
                'max_age' => null,
                'min_weight' => 67,
                'max_weight' => null,
            ],
            // JUVENIL (15-17 años): Peso Olímpico
            [
                'name' => 'Juvenil -48 kg',
                'type' => 'Para-Kyorugui',
                'gender' => 'M',
                'min_age' => 15,
                'max_age' => 17,
                'min_weight' => 0,
                'max_weight' => 48,
            ],
            [
                'name' => 'Juvenil -44 kg',
                'type' => 'Para-Kyorugui',
                'gender' => 'F',
                'min_age' => 15,
                'max_age' => 17,
                'min_weight' => 0,
                'max_weight' => 44,
            ],
            [
                'name' => 'Juvenil -55 kg',
                'type' => 'Para-Kyorugui',
                'gender' => 'M',
                'min_age' => 15,
                'max_age' => 17,
                'min_weight' => 48,
                'max_weight' => 55,
            ],
            [
                'name' => 'Juvenil -49 kg',
                'type' => 'Para-Kyorugui',
                'gender' => 'F',
                'min_age' => 15,
                'max_age' => 17,
                'min_weight' => 44,
                'max_weight' => 49,
            ],
            [
                'name' => 'Juvenil -63 kg',
                'type' => 'Para-Kyorugui',
                'gender' => 'M',
                'min_age' => 15,
                'max_age' => 17,
                'min_weight' => 55,
                'max_weight' => 63,
            ],
            [
                'name' => 'Juvenil -55 kg',
                'type' => 'Para-Kyorugui',
                'gender' => 'F',
                'min_age' => 15,
                'max_age' => 17,
                'min_weight' => 49,
                'max_weight' => 55,
            ],
            [
                'name' => 'Juvenil -73 kg',
                'type' => 'Para-Kyorugui',
                'gender' => 'M',
                'min_age' => 15,
                'max_age' => 17,
                'min_weight' => 63,
                'max_weight' => 73,
            ],
            [
                'name' => 'Juvenil -63 kg',
                'type' => 'Para-Kyorugui',
                'gender' => 'F',
                'min_age' => 15,
                'max_age' => 17,
                'min_weight' => 55,
                'max_weight' => 63,
            ],
            [
                'name' => 'Juvenil +73 kg',
                'type' => 'Para-Kyorugui',
                'gender' => 'M',
                'min_age' => 15,
                'max_age' => 17,
                'min_weight' => 73,
                'max_weight' => null,
            ],
            [
                'name' => 'Juvenil +63 kg',
                'type' => 'Para-Kyorugui',
                'gender' => 'F',
                'min_age' => 15,
                'max_age' => 17,
                'min_weight' => 63,
                'max_weight' => null,
            ],
            // POOMSAE
            [
            'name' => 'Infantil',
            'type' => 'Poomsae',
            'gender' => 'M',
            'min_age' => 3,
            'max_age' => 11,
            ],
            [
                'name' => 'Cadete',
                'type' => 'Poomsae',
                'gender' => 'M',
                'min_age' => 12,
                'max_age' => 14,
            ],
            [
                'name' => 'Juvenil',
                'type' => 'Poomsae',
                'gender' => 'M',
                'min_age' => 15,
                'max_age' => 17,
            ],
            [
                'name' => 'Adulto',
                'type' => 'Poomsae',
                'gender' => 'M',
                'min_age' => 18,
                'max_age' => 35,
            ],
            [
                'name' => 'Infantil',
                'type' => 'Poomsae',
                'gender' => 'F',
                'min_age' => 3,
                'max_age' => 11,
            ],
            [
                'name' => 'Cadete',
                'type' => 'Poomsae',
                'gender' => 'F',
                'min_age' => 12,
                'max_age' => 14,
            ],
            [
                'name' => 'Juvenil',
                'type' => 'Poomsae',
                'gender' => 'F',
                'min_age' => 15,
                'max_age' => 17,
            ],
            [
                'name' => 'Adulto',
                'type' => 'Poomsae',
                'gender' => 'F',
                'min_age' => 18,
                'max_age' => 35,
            ],
            // POOMSAE
            [
                'name' => 'Infantil',
                'type' => 'Poomsae',
                'gender' => 'Mixed',
                'min_age' => 3,
                'max_age' => 11,
                'description' => 'Taegeuk 4, 5, 6, 7, 8 Jang, Koryo, Keumgang, Taeback',
            ],
            [
                'name' => 'Cadete',
                'type' => 'Poomsae',
                'gender' => 'Mixed',
                'min_age' => 12,
                'max_age' => 14,
                'description' => 'Taegeuk 4, 5, 6, 7, 8 Jang, Koryo, Keumgang, Taeback',
            ],
            [
                'name' => 'Juvenil',
                'type' => 'Poomsae',
                'gender' => 'Mixed',
                'min_age' => 15,
                'max_age' => 17,
                'description' => 'Taegeuk 5, 6, 7, 8 Jang, Koryo, Keumgang, Taeback, Pyongwon',
            ],
            [
                'name' => 'U-30 años',
                'type' => 'Poomsae',
                'gender' => 'Mixed',
                'min_age' => 18,
                'max_age' => 30,
                'description' => 'Taegeuk 7, 8 Jang, Koryo, Keumgang, Taeback, Pyongwon, Shipjin, Jitae',
            ],
            [
                'name' => 'U-40 años',
                'type' => 'Poomsae',
                'gender' => 'Mixed',
                'min_age' => 31,
                'max_age' => 40,
                'description' => 'Taegeuk 8 Jang, Koryo, Keumgang, Taeback, Pyongwon, Shipjin, Jitae, Chonkwon',
            ],
            [
                'name' => 'U-50 años',
                'type' => 'Poomsae',
                'gender' => 'Mixed',
                'min_age' => 41,
                'max_age' => 50,
                'description' => 'Taegeuk 8 Jang, Koryo, Keumgang, Taeback, Pyongwon, Shipjin, Jitae, Chonkwon',
            ],
            [
                'name' => 'U-60 años',
                'type' => 'Poomsae',
                'gender' => 'Mixed',
                'min_age' => 51,
                'max_age' => 60,
                'description' => 'Koryo, Keumgang, Taeback, Pyongwon, Shipjin, Jitae, Chonkwon, Hansu',
            ],
            [
                'name' => 'U+65 años',
                'type' => 'Poomsae',
                'gender' => 'Mixed',
                'min_age' => 66,
                'max_age' => null,
                'description' => 'Koryo, Keumgang, Taeback, Pyongwon, Shipjin, Jitae, Chonkwon, Hansu',
            ],    
            // PARA-POOMSAE
            [
                'name' => 'Infantil',
                'type' => 'Para-Poomsae',
                'gender' => 'Mixed',
                'min_age' => 3,
                'max_age' => 11,
                'description' => 'Taegeuk 4, 5, 6, 7, 8 Jang, Koryo, Keumgang, Taeback',
            ],
            [
                'name' => 'Cadete',
                'type' => 'Para-Poomsae',
                'gender' => 'Mixed',
                'min_age' => 12,
                'max_age' => 14,
                'description' => 'Taegeuk 4, 5, 6, 7, 8 Jang, Koryo, Keumgang, Taeback',
            ],
            [
                'name' => 'Juvenil',
                'type' => 'Para-Poomsae',
                'gender' => 'Mixed',
                'min_age' => 15,
                'max_age' => 17,
                'description' => 'Taegeuk 5, 6, 7, 8 Jang, Koryo, Keumgang, Taeback, Pyongwon',
            ],
            [
                'name' => 'U-30 años',
                'type' => 'Para-Poomsae',
                'gender' => 'Mixed',
                'min_age' => 18,
                'max_age' => 30,
                'description' => 'Taegeuk 7, 8 Jang, Koryo, Keumgang, Taeback, Pyongwon, Shipjin, Jitae',
            ],
            [
                'name' => 'U-40 años',
                'type' => 'Para-Poomsae',
                'gender' => 'Mixed',
                'min_age' => 31,
                'max_age' => 40,
                'description' => 'Taegeuk 8 Jang, Koryo, Keumgang, Taeback, Pyongwon, Shipjin, Jitae, Chonkwon',
            ],
            [
                'name' => 'U-50 años',
                'type' => 'Para-Poomsae',
                'gender' => 'Mixed',
                'min_age' => 41,
                'max_age' => 50,
                'description' => 'Taegeuk 8 Jang, Koryo, Keumgang, Taeback, Pyongwon, Shipjin, Jitae, Chonkwon',
            ],
            [
                'name' => 'U-60 años',
                'type' => 'Para-Poomsae',
                'gender' => 'Mixed',
                'min_age' => 51,
                'max_age' => 60,
                'description' => 'Koryo, Keumgang, Taeback, Pyongwon, Shipjin, Jitae, Chonkwon, Hansu',
            ],
            [
                'name' => 'U+65 años',
                'type' => 'Para-Poomsae',
                'gender' => 'Mixed',
                'min_age' => 66,
                'max_age' => null,
                'description' => 'Koryo, Keumgang, Taeback, Pyongwon, Shipjin, Jitae, Chonkwon, Hansu',
            ],
            
        ];

        foreach ($categories as $categoryData) {
            Category::create($categoryData);
        }
    }
}
